[2025-03-12T23:31:01.002+0000] {processor.py:186} INFO - Started process (PID=76) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:31:01.005+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:31:01.011+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:31:01.010+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:31:01.038+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:31:01.034+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:31:01.039+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:31:01.090+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.100 seconds
[2025-03-12T23:31:31.638+0000] {processor.py:186} INFO - Started process (PID=143) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:31:31.641+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:31:31.649+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:31:31.649+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:31:31.687+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:31:31.684+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:31:31.689+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:31:31.739+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.108 seconds
[2025-03-12T23:32:02.711+0000] {processor.py:186} INFO - Started process (PID=209) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:32:02.712+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:32:02.714+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:32:02.714+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:32:02.732+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:32:02.731+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:32:02.733+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:32:02.755+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.050 seconds
[2025-03-12T23:32:33.696+0000] {processor.py:186} INFO - Started process (PID=275) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:32:33.698+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:32:33.708+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:32:33.707+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:32:33.733+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:32:33.731+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:32:33.734+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:32:33.765+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.076 seconds
[2025-03-12T23:33:03.850+0000] {processor.py:186} INFO - Started process (PID=341) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:33:03.852+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:33:03.856+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:33:03.856+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:33:03.876+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:33:03.875+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:33:03.877+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:33:03.911+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.067 seconds
[2025-03-12T23:33:34.289+0000] {processor.py:186} INFO - Started process (PID=407) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:33:34.293+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:33:34.301+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:33:34.300+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:33:34.327+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:33:34.325+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:33:34.328+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:33:34.362+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.079 seconds
[2025-03-12T23:34:04.814+0000] {processor.py:186} INFO - Started process (PID=473) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:34:04.815+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:34:04.817+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:34:04.817+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:34:04.848+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:34:04.846+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:34:04.849+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:34:04.890+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.084 seconds
[2025-03-12T23:34:35.311+0000] {processor.py:186} INFO - Started process (PID=539) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:34:35.312+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:34:35.314+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:34:35.313+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:34:35.335+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:34:35.333+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:34:35.335+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:34:35.363+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.060 seconds
[2025-03-12T23:35:05.679+0000] {processor.py:186} INFO - Started process (PID=605) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:35:05.681+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:35:05.683+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:35:05.683+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:35:05.704+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:35:05.703+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:35:05.705+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:35:05.735+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.063 seconds
[2025-03-12T23:35:35.968+0000] {processor.py:186} INFO - Started process (PID=671) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:35:35.970+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:35:35.973+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:35:35.972+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:35:36.003+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:35:36.001+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:35:36.005+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:35:36.047+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.087 seconds
[2025-03-12T23:36:06.997+0000] {processor.py:186} INFO - Started process (PID=737) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:36:06.999+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:36:07.001+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:36:07.001+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:36:07.022+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:36:07.021+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:36:07.023+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:36:07.051+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.061 seconds
[2025-03-12T23:36:37.406+0000] {processor.py:186} INFO - Started process (PID=803) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:36:37.408+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:36:37.410+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:36:37.409+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:36:37.425+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:36:37.424+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:36:37.426+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:36:37.451+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.050 seconds
[2025-03-12T23:37:07.653+0000] {processor.py:186} INFO - Started process (PID=869) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:37:07.658+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:37:07.663+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:37:07.663+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:37:07.691+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:37:07.689+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:37:07.694+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:37:07.734+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.095 seconds
[2025-03-12T23:37:38.562+0000] {processor.py:186} INFO - Started process (PID=935) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:37:38.563+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:37:38.565+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:37:38.565+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:37:38.581+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:37:38.580+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:37:38.582+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:37:38.603+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.047 seconds
[2025-03-12T23:38:09.558+0000] {processor.py:186} INFO - Started process (PID=1000) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:38:09.560+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:38:09.561+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:38:09.561+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:38:09.578+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:38:09.577+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:38:09.579+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:38:09.600+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.047 seconds
[2025-03-12T23:38:40.621+0000] {processor.py:186} INFO - Started process (PID=1066) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:38:40.622+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:38:40.625+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:38:40.624+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:38:40.642+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:38:40.641+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:38:40.643+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:38:40.667+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.053 seconds
[2025-03-12T23:39:11.641+0000] {processor.py:186} INFO - Started process (PID=1132) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:39:11.642+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:39:11.644+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:39:11.644+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:39:11.661+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:39:11.660+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:39:11.661+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:39:11.681+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.046 seconds
[2025-03-12T23:39:41.877+0000] {processor.py:186} INFO - Started process (PID=1199) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:39:41.878+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:39:41.880+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:39:41.879+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:39:41.896+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:39:41.895+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:39:41.897+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:39:41.917+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.045 seconds
[2025-03-12T23:40:12.404+0000] {processor.py:186} INFO - Started process (PID=1265) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:40:12.405+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:40:12.407+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:40:12.406+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:40:12.473+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:40:12.472+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:40:12.475+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:40:12.521+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.127 seconds
[2025-03-12T23:40:43.245+0000] {processor.py:186} INFO - Started process (PID=1331) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:40:43.246+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:40:43.247+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:40:43.247+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:40:43.263+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:40:43.262+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:40:43.264+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:40:43.286+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.047 seconds
[2025-03-12T23:41:13.986+0000] {processor.py:186} INFO - Started process (PID=1397) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:41:13.987+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:41:13.989+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:41:13.988+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:41:14.007+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:41:14.005+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:41:14.008+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:41:14.032+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.053 seconds
[2025-03-12T23:41:44.325+0000] {processor.py:186} INFO - Started process (PID=1464) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:41:44.329+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:41:44.331+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:41:44.330+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:41:44.360+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:41:44.358+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:41:44.361+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:41:44.400+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.090 seconds
[2025-03-12T23:42:14.709+0000] {processor.py:186} INFO - Started process (PID=1530) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:42:14.710+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:42:14.711+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:42:14.711+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:42:14.728+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:42:14.727+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:42:14.729+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:42:14.752+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.049 seconds
[2025-03-12T23:42:45.546+0000] {processor.py:186} INFO - Started process (PID=1596) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:42:45.547+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:42:45.549+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:42:45.548+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:42:45.567+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:42:45.565+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:42:45.567+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:42:45.588+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.048 seconds
[2025-03-12T23:43:15.766+0000] {processor.py:186} INFO - Started process (PID=1662) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:43:15.769+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:43:15.771+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:43:15.770+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:43:15.794+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:43:15.792+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:43:15.795+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:43:15.817+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.060 seconds
[2025-03-12T23:43:47.117+0000] {processor.py:186} INFO - Started process (PID=1726) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:43:47.119+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:43:47.121+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:43:47.120+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:43:47.139+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:43:47.138+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:43:47.140+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:43:47.164+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.053 seconds
[2025-03-12T23:44:18.375+0000] {processor.py:186} INFO - Started process (PID=1792) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:44:18.378+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:44:18.387+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:44:18.386+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:44:18.408+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:44:18.407+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:44:18.408+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:44:18.434+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.065 seconds
[2025-03-12T23:44:49.316+0000] {processor.py:186} INFO - Started process (PID=1855) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:44:49.317+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:44:49.319+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:44:49.319+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:44:49.367+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:44:49.366+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:44:49.368+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:44:49.399+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.100 seconds
[2025-03-12T23:45:19.889+0000] {processor.py:186} INFO - Started process (PID=1915) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:45:19.892+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:45:19.896+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:45:19.895+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:45:19.944+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:45:19.942+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:45:19.945+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:45:19.969+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.092 seconds
[2025-03-12T23:45:50.785+0000] {processor.py:186} INFO - Started process (PID=1981) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:45:50.786+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:45:50.788+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:45:50.787+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:45:50.803+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:45:50.801+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:45:50.804+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:45:50.825+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.045 seconds
[2025-03-12T23:46:20.875+0000] {processor.py:186} INFO - Started process (PID=2047) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:46:20.876+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:46:20.882+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:46:20.881+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:46:20.918+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:46:20.917+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:46:20.920+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:46:20.955+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.085 seconds
[2025-03-12T23:46:51.295+0000] {processor.py:186} INFO - Started process (PID=2113) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:46:51.297+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:46:51.300+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:46:51.299+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:46:51.322+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:46:51.320+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:46:51.324+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:46:51.361+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.075 seconds
[2025-03-12T23:47:21.527+0000] {processor.py:186} INFO - Started process (PID=2179) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:47:21.528+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:47:21.530+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:47:21.529+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:47:21.551+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:47:21.550+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:47:21.552+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:47:21.581+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.061 seconds
[2025-03-12T23:47:51.905+0000] {processor.py:186} INFO - Started process (PID=2238) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:47:51.907+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:47:51.910+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:47:51.909+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:47:51.930+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:47:51.929+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:47:51.931+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:47:51.957+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.059 seconds
[2025-03-12T23:48:22.454+0000] {processor.py:186} INFO - Started process (PID=2304) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:48:22.456+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:48:22.460+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:48:22.459+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:48:22.492+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:48:22.490+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:48:22.493+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:48:22.517+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.079 seconds
[2025-03-12T23:48:53.194+0000] {processor.py:186} INFO - Started process (PID=2370) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:48:53.195+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:48:53.197+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:48:53.197+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:48:53.229+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:48:53.228+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:48:53.230+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:48:53.262+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.077 seconds
[2025-03-12T23:49:23.578+0000] {processor.py:186} INFO - Started process (PID=2442) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:49:23.580+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:49:23.584+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:49:23.584+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:49:23.619+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:49:23.617+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:49:23.621+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:49:23.671+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.107 seconds
[2025-03-12T23:49:54.144+0000] {processor.py:186} INFO - Started process (PID=2507) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:49:54.145+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:49:54.147+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:49:54.146+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:49:54.168+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:49:54.166+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:49:54.169+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:49:54.197+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.060 seconds
[2025-03-12T23:50:24.426+0000] {processor.py:186} INFO - Started process (PID=2574) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:50:24.427+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:50:24.429+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:50:24.429+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:50:24.448+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:50:24.447+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:50:24.449+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:50:24.473+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.055 seconds
[2025-03-12T23:50:55.321+0000] {processor.py:186} INFO - Started process (PID=2640) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:50:55.323+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:50:55.326+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:50:55.325+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:50:55.345+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:50:55.344+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:50:55.347+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:50:55.375+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.061 seconds
[2025-03-12T23:51:26.208+0000] {processor.py:186} INFO - Started process (PID=2706) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:51:26.211+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:51:26.212+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:51:26.212+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:51:26.234+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:51:26.233+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:51:26.235+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:51:26.262+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.062 seconds
[2025-03-12T23:51:57.061+0000] {processor.py:186} INFO - Started process (PID=2772) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:51:57.064+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:51:57.068+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:51:57.067+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:51:57.138+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:51:57.135+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:51:57.141+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:51:57.202+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.158 seconds
[2025-03-12T23:52:27.423+0000] {processor.py:186} INFO - Started process (PID=2838) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:52:27.425+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:52:27.426+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:52:27.426+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:52:27.444+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:52:27.442+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:52:27.445+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:52:27.469+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.052 seconds
[2025-03-12T23:52:57.670+0000] {processor.py:186} INFO - Started process (PID=2904) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:52:57.671+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:52:57.672+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:52:57.672+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:52:57.686+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:52:57.685+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:52:57.687+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:52:57.707+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.042 seconds
[2025-03-12T23:53:27.781+0000] {processor.py:186} INFO - Started process (PID=2970) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:53:27.782+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:53:27.783+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:53:27.783+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:53:27.796+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:53:27.795+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:53:27.796+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:53:27.813+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.037 seconds
[2025-03-12T23:53:57.991+0000] {processor.py:186} INFO - Started process (PID=3036) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:53:57.992+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:53:57.994+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:53:57.993+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:53:58.007+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:53:58.006+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:53:58.008+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:53:58.029+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.043 seconds
[2025-03-12T23:54:28.250+0000] {processor.py:186} INFO - Started process (PID=3102) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:54:28.251+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:54:28.253+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:54:28.252+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:54:28.269+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:54:28.268+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:54:28.270+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:54:28.292+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.049 seconds
[2025-03-12T23:54:58.837+0000] {processor.py:186} INFO - Started process (PID=3168) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:54:58.838+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:54:58.840+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:54:58.840+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:54:58.858+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:54:58.857+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:54:58.859+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:54:58.887+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.056 seconds
[2025-03-12T23:55:29.150+0000] {processor.py:186} INFO - Started process (PID=3234) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:55:29.151+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:55:29.152+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:55:29.152+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:55:29.166+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:55:29.165+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:55:29.167+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:55:29.185+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.040 seconds
[2025-03-12T23:55:59.764+0000] {processor.py:186} INFO - Started process (PID=3300) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:55:59.765+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:55:59.767+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:55:59.766+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:55:59.782+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:55:59.781+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:55:59.783+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:55:59.803+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.044 seconds
[2025-03-12T23:56:30.320+0000] {processor.py:186} INFO - Started process (PID=3366) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:56:30.322+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:56:30.323+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:56:30.322+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:56:30.337+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:56:30.336+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:56:30.337+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:56:30.357+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.041 seconds
[2025-03-12T23:57:00.924+0000] {processor.py:186} INFO - Started process (PID=3432) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:57:00.925+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:57:00.926+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:57:00.926+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:57:00.944+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:57:00.941+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:57:00.948+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:57:00.970+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.053 seconds
[2025-03-12T23:57:31.704+0000] {processor.py:186} INFO - Started process (PID=3498) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:57:31.705+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:57:31.707+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:57:31.706+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:57:31.721+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:57:31.720+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:57:31.722+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:57:31.742+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.044 seconds
[2025-03-12T23:58:02.027+0000] {processor.py:186} INFO - Started process (PID=3564) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:58:02.028+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:58:02.029+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:58:02.029+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:58:02.043+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:58:02.042+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:58:02.044+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:58:02.064+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.042 seconds
[2025-03-12T23:58:32.873+0000] {processor.py:186} INFO - Started process (PID=3630) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:58:32.874+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:58:32.875+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:58:32.875+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:58:32.890+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:58:32.889+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:58:32.890+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:58:32.914+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.046 seconds
[2025-03-12T23:59:03.779+0000] {processor.py:186} INFO - Started process (PID=3696) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:59:03.780+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:59:03.782+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:59:03.781+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:59:03.802+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:59:03.801+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:59:03.803+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:59:03.825+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.051 seconds
[2025-03-12T23:59:34.430+0000] {processor.py:186} INFO - Started process (PID=3762) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:59:34.431+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:59:34.433+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:59:34.432+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:59:34.451+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:59:34.450+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:59:34.452+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:59:34.476+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.052 seconds
