[2025-03-12T23:31:01.002+0000] {processor.py:186} INFO - Started process (PID=76) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:31:01.005+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:31:01.011+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:31:01.010+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:31:01.038+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:31:01.034+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:31:01.039+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:31:01.090+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.100 seconds
[2025-03-12T23:31:31.638+0000] {processor.py:186} INFO - Started process (PID=143) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:31:31.641+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:31:31.649+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:31:31.649+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:31:31.687+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:31:31.684+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:31:31.689+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:31:31.739+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.108 seconds
[2025-03-12T23:32:02.711+0000] {processor.py:186} INFO - Started process (PID=209) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:32:02.712+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:32:02.714+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:32:02.714+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:32:02.732+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:32:02.731+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:32:02.733+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:32:02.755+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.050 seconds
[2025-03-12T23:32:33.696+0000] {processor.py:186} INFO - Started process (PID=275) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:32:33.698+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:32:33.708+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:32:33.707+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:32:33.733+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:32:33.731+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:32:33.734+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:32:33.765+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.076 seconds
[2025-03-12T23:33:03.850+0000] {processor.py:186} INFO - Started process (PID=341) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:33:03.852+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:33:03.856+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:33:03.856+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:33:03.876+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:33:03.875+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:33:03.877+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:33:03.911+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.067 seconds
[2025-03-12T23:33:34.289+0000] {processor.py:186} INFO - Started process (PID=407) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:33:34.293+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:33:34.301+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:33:34.300+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:33:34.327+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:33:34.325+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:33:34.328+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:33:34.362+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.079 seconds
[2025-03-12T23:34:04.814+0000] {processor.py:186} INFO - Started process (PID=473) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:34:04.815+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:34:04.817+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:34:04.817+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:34:04.848+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:34:04.846+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:34:04.849+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:34:04.890+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.084 seconds
[2025-03-12T23:34:35.311+0000] {processor.py:186} INFO - Started process (PID=539) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:34:35.312+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:34:35.314+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:34:35.313+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:34:35.335+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:34:35.333+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:34:35.335+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:34:35.363+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.060 seconds
[2025-03-12T23:35:05.679+0000] {processor.py:186} INFO - Started process (PID=605) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:35:05.681+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:35:05.683+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:35:05.683+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:35:05.704+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:35:05.703+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:35:05.705+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:35:05.735+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.063 seconds
[2025-03-12T23:35:35.968+0000] {processor.py:186} INFO - Started process (PID=671) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:35:35.970+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:35:35.973+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:35:35.972+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:35:36.003+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:35:36.001+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:35:36.005+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:35:36.047+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.087 seconds
[2025-03-12T23:36:06.997+0000] {processor.py:186} INFO - Started process (PID=737) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:36:06.999+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:36:07.001+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:36:07.001+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:36:07.022+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:36:07.021+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:36:07.023+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:36:07.051+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.061 seconds
[2025-03-12T23:36:37.406+0000] {processor.py:186} INFO - Started process (PID=803) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:36:37.408+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:36:37.410+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:36:37.409+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:36:37.425+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:36:37.424+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:36:37.426+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:36:37.451+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.050 seconds
[2025-03-12T23:37:07.653+0000] {processor.py:186} INFO - Started process (PID=869) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:37:07.658+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:37:07.663+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:37:07.663+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:37:07.691+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:37:07.689+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:37:07.694+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:37:07.734+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.095 seconds
[2025-03-12T23:37:38.562+0000] {processor.py:186} INFO - Started process (PID=935) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:37:38.563+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:37:38.565+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:37:38.565+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:37:38.581+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:37:38.580+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:37:38.582+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:37:38.603+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.047 seconds
[2025-03-12T23:38:09.558+0000] {processor.py:186} INFO - Started process (PID=1000) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:38:09.560+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:38:09.561+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:38:09.561+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:38:09.578+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:38:09.577+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:38:09.579+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:38:09.600+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.047 seconds
[2025-03-12T23:38:40.621+0000] {processor.py:186} INFO - Started process (PID=1066) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:38:40.622+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:38:40.625+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:38:40.624+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:38:40.642+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:38:40.641+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:38:40.643+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:38:40.667+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.053 seconds
[2025-03-12T23:39:11.641+0000] {processor.py:186} INFO - Started process (PID=1132) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:39:11.642+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:39:11.644+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:39:11.644+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:39:11.661+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:39:11.660+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:39:11.661+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:39:11.681+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.046 seconds
[2025-03-12T23:39:41.877+0000] {processor.py:186} INFO - Started process (PID=1199) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:39:41.878+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:39:41.880+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:39:41.879+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:39:41.896+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:39:41.895+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:39:41.897+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:39:41.917+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.045 seconds
[2025-03-12T23:40:12.404+0000] {processor.py:186} INFO - Started process (PID=1265) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:40:12.405+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:40:12.407+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:40:12.406+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:40:12.473+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:40:12.472+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:40:12.475+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:40:12.521+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.127 seconds
[2025-03-12T23:40:43.245+0000] {processor.py:186} INFO - Started process (PID=1331) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:40:43.246+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:40:43.247+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:40:43.247+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:40:43.263+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:40:43.262+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:40:43.264+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:40:43.286+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.047 seconds
[2025-03-12T23:41:13.986+0000] {processor.py:186} INFO - Started process (PID=1397) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:41:13.987+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:41:13.989+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:41:13.988+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:41:14.007+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:41:14.005+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:41:14.008+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:41:14.032+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.053 seconds
[2025-03-12T23:41:44.325+0000] {processor.py:186} INFO - Started process (PID=1464) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:41:44.329+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:41:44.331+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:41:44.330+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:41:44.360+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:41:44.358+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:41:44.361+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:41:44.400+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.090 seconds
[2025-03-12T23:42:14.709+0000] {processor.py:186} INFO - Started process (PID=1530) to work on /opt/airflow/dags/pipeline.py
[2025-03-12T23:42:14.710+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-12T23:42:14.711+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:42:14.711+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-12T23:42:14.728+0000] {logging_mixin.py:190} INFO - [2025-03-12T23:42:14.727+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-12T23:42:14.729+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-12T23:42:14.752+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.049 seconds
