[2025-03-10T00:00:30.456+0000] {processor.py:186} INFO - Started process (PID=47053) to work on /opt/airflow/dags/pipeline.py
[2025-03-10T00:00:30.457+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-10T00:00:30.459+0000] {logging_mixin.py:190} INFO - [2025-03-10T00:00:30.459+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-10T00:00:30.473+0000] {logging_mixin.py:190} INFO - [2025-03-10T00:00:30.472+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-10T00:00:30.476+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-10T00:00:30.492+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.041 seconds
[2025-03-10T00:01:01.325+0000] {processor.py:186} INFO - Started process (PID=47119) to work on /opt/airflow/dags/pipeline.py
[2025-03-10T00:01:01.326+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-10T00:01:01.328+0000] {logging_mixin.py:190} INFO - [2025-03-10T00:01:01.327+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-10T00:01:01.341+0000] {logging_mixin.py:190} INFO - [2025-03-10T00:01:01.340+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-10T00:01:01.342+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-10T00:01:01.358+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.037 seconds
[2025-03-10T00:01:32.135+0000] {processor.py:186} INFO - Started process (PID=47185) to work on /opt/airflow/dags/pipeline.py
[2025-03-10T00:01:32.136+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-10T00:01:32.137+0000] {logging_mixin.py:190} INFO - [2025-03-10T00:01:32.136+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-10T00:01:32.150+0000] {logging_mixin.py:190} INFO - [2025-03-10T00:01:32.149+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-10T00:01:32.150+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-10T00:01:32.167+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.036 seconds
[2025-03-10T00:02:02.293+0000] {processor.py:186} INFO - Started process (PID=47251) to work on /opt/airflow/dags/pipeline.py
[2025-03-10T00:02:02.294+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-10T00:02:02.295+0000] {logging_mixin.py:190} INFO - [2025-03-10T00:02:02.295+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-10T00:02:02.309+0000] {logging_mixin.py:190} INFO - [2025-03-10T00:02:02.308+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-10T00:02:02.309+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-10T00:02:02.326+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.038 seconds
[2025-03-10T00:02:32.860+0000] {processor.py:186} INFO - Started process (PID=47317) to work on /opt/airflow/dags/pipeline.py
[2025-03-10T00:02:32.861+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-10T00:02:32.863+0000] {logging_mixin.py:190} INFO - [2025-03-10T00:02:32.863+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-10T00:02:32.877+0000] {logging_mixin.py:190} INFO - [2025-03-10T00:02:32.876+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-10T00:02:32.878+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-10T00:02:32.895+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.039 seconds
[2025-03-10T00:03:02.963+0000] {processor.py:186} INFO - Started process (PID=47383) to work on /opt/airflow/dags/pipeline.py
[2025-03-10T00:03:02.964+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-10T00:03:02.966+0000] {logging_mixin.py:190} INFO - [2025-03-10T00:03:02.966+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-10T00:03:02.983+0000] {logging_mixin.py:190} INFO - [2025-03-10T00:03:02.982+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-10T00:03:02.984+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-10T00:03:03.005+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.049 seconds
[2025-03-10T00:03:33.586+0000] {processor.py:186} INFO - Started process (PID=47449) to work on /opt/airflow/dags/pipeline.py
[2025-03-10T00:03:33.587+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-10T00:03:33.589+0000] {logging_mixin.py:190} INFO - [2025-03-10T00:03:33.589+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-10T00:03:33.602+0000] {logging_mixin.py:190} INFO - [2025-03-10T00:03:33.601+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-10T00:03:33.603+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-10T00:03:33.621+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.039 seconds
[2025-03-10T00:04:03.970+0000] {processor.py:186} INFO - Started process (PID=47515) to work on /opt/airflow/dags/pipeline.py
[2025-03-10T00:04:03.971+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-10T00:04:03.973+0000] {logging_mixin.py:190} INFO - [2025-03-10T00:04:03.972+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-10T00:04:03.991+0000] {logging_mixin.py:190} INFO - [2025-03-10T00:04:03.989+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-10T00:04:03.992+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-10T00:04:04.014+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.050 seconds
[2025-03-10T00:04:34.573+0000] {processor.py:186} INFO - Started process (PID=47581) to work on /opt/airflow/dags/pipeline.py
[2025-03-10T00:04:34.573+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-10T00:04:34.575+0000] {logging_mixin.py:190} INFO - [2025-03-10T00:04:34.574+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-10T00:04:34.588+0000] {logging_mixin.py:190} INFO - [2025-03-10T00:04:34.586+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-10T00:04:34.588+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-10T00:04:34.607+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.039 seconds
[2025-03-10T00:05:05.358+0000] {processor.py:186} INFO - Started process (PID=47647) to work on /opt/airflow/dags/pipeline.py
[2025-03-10T00:05:05.360+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-10T00:05:05.361+0000] {logging_mixin.py:190} INFO - [2025-03-10T00:05:05.361+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-10T00:05:05.379+0000] {logging_mixin.py:190} INFO - [2025-03-10T00:05:05.378+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-10T00:05:05.379+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-10T00:05:05.397+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.043 seconds
[2025-03-10T00:05:35.923+0000] {processor.py:186} INFO - Started process (PID=47713) to work on /opt/airflow/dags/pipeline.py
[2025-03-10T00:05:35.924+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-10T00:05:35.925+0000] {logging_mixin.py:190} INFO - [2025-03-10T00:05:35.924+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-10T00:05:35.938+0000] {logging_mixin.py:190} INFO - [2025-03-10T00:05:35.937+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-10T00:05:35.939+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-10T00:05:35.957+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.039 seconds
[2025-03-10T00:06:06.691+0000] {processor.py:186} INFO - Started process (PID=47779) to work on /opt/airflow/dags/pipeline.py
[2025-03-10T00:06:06.692+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-10T00:06:06.693+0000] {logging_mixin.py:190} INFO - [2025-03-10T00:06:06.693+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-10T00:06:06.706+0000] {logging_mixin.py:190} INFO - [2025-03-10T00:06:06.705+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-10T00:06:06.706+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-10T00:06:06.726+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.039 seconds
[2025-03-10T00:06:37.090+0000] {processor.py:186} INFO - Started process (PID=47849) to work on /opt/airflow/dags/pipeline.py
[2025-03-10T00:06:37.091+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-10T00:06:37.092+0000] {logging_mixin.py:190} INFO - [2025-03-10T00:06:37.092+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-10T00:06:37.107+0000] {logging_mixin.py:190} INFO - [2025-03-10T00:06:37.106+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-10T00:06:37.107+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-10T00:06:37.127+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.043 seconds
[2025-03-10T00:07:07.461+0000] {processor.py:186} INFO - Started process (PID=47912) to work on /opt/airflow/dags/pipeline.py
[2025-03-10T00:07:07.462+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-10T00:07:07.463+0000] {logging_mixin.py:190} INFO - [2025-03-10T00:07:07.463+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-10T00:07:07.477+0000] {logging_mixin.py:190} INFO - [2025-03-10T00:07:07.476+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-10T00:07:07.478+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-10T00:07:07.496+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.040 seconds
