[2025-03-09T19:15:51.136+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-09T19:15:51.153+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: processar_emails_excel_operador_personalizado.ler_emails_microsoft_graph scheduled__2025-03-08T00:00:00+00:00 [queued]>
[2025-03-09T19:15:51.161+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: processar_emails_excel_operador_personalizado.ler_emails_microsoft_graph scheduled__2025-03-08T00:00:00+00:00 [queued]>
[2025-03-09T19:15:51.162+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-03-09T19:15:51.175+0000] {taskinstance.py:2889} INFO - Executing <Task(MicrosoftGraphEmail): ler_emails_microsoft_graph> on 2025-03-08 00:00:00+00:00
[2025-03-09T19:15:51.185+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'processar_emails_excel_operador_personalizado', 'ler_emails_microsoft_graph', 'scheduled__2025-03-08T00:00:00+00:00', '--job-id', '151', '--raw', '--subdir', 'DAGS_FOLDER/extraiEmail.py', '--cfg-path', '/tmp/tmp_btiq7km']
[2025-03-09T19:15:51.184+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1164) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-09T19:15:51.186+0000] {standard_task_runner.py:105} INFO - Job 151: Subtask ler_emails_microsoft_graph
[2025-03-09T19:15:51.187+0000] {standard_task_runner.py:72} INFO - Started process 1166 to run task
[2025-03-09T19:15:51.431+0000] {task_command.py:467} INFO - Running <TaskInstance: processar_emails_excel_operador_personalizado.ler_emails_microsoft_graph scheduled__2025-03-08T00:00:00+00:00 [running]> on host 4052a614e333
[2025-03-09T19:15:51.507+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='processar_emails_excel_operador_personalizado' AIRFLOW_CTX_TASK_ID='ler_emails_microsoft_graph' AIRFLOW_CTX_EXECUTION_DATE='2025-03-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-08T00:00:00+00:00'
[2025-03-09T19:15:51.508+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-09T19:15:51.508+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-09T19:15:51.508+0000] {logging_mixin.py:190} INFO - Current task name:ler_emails_microsoft_graph state:running start_date:2025-03-09 19:15:51.154262+00:00
[2025-03-09T19:15:51.509+0000] {logging_mixin.py:190} INFO - Dag name:processar_emails_excel_operador_personalizado and current dag run status:running
[2025-03-09T19:15:51.510+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-09T19:15:51.821+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/extrai_email_operator.py", line 25, in execute
    token = self._get_access_token()
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/extrai_email_operator.py", line 43, in _get_access_token
    raise Exception(f"Erro ao obter o token: {response.status_code}, {response.text}")
Exception: Erro ao obter o token: 400, {"error":"invalid_request","error_description":"AADSTS900023: Specified tenant identifier 'seu_tenant_id' is neither a valid DNS name, nor a valid external domain. Trace ID: 1e769860-8b10-479e-abf6-84f3fac7ae00 Correlation ID: 50b2ae58-33be-4671-a3a0-c1283361a670 Timestamp: 2025-03-09 19:15:52Z","error_codes":[900023],"timestamp":"2025-03-09 19:15:52Z","trace_id":"1e769860-8b10-479e-abf6-84f3fac7ae00","correlation_id":"50b2ae58-33be-4671-a3a0-c1283361a670","error_uri":"https://login.microsoftonline.com/error?code=900023"}
[2025-03-09T19:15:51.840+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-09T19:15:51.840+0000] {logging_mixin.py:190} INFO - Task start:2025-03-09 19:15:51.154262+00:00 end:2025-03-09 19:15:51.839687+00:00 duration:0.685425
[2025-03-09T19:15:51.841+0000] {logging_mixin.py:190} INFO - Task:<Task(MicrosoftGraphEmail): ler_emails_microsoft_graph> dag:<DAG: processar_emails_excel_operador_personalizado> dagrun:<DagRun processar_emails_excel_operador_personalizado @ 2025-03-08 00:00:00+00:00: scheduled__2025-03-08T00:00:00+00:00, state:running, queued_at: 2025-03-09 19:15:49.085569+00:00. externally triggered: False>
[2025-03-09T19:15:51.842+0000] {logging_mixin.py:190} INFO - Failure caused by Erro ao obter o token: 400, {"error":"invalid_request","error_description":"AADSTS900023: Specified tenant identifier 'seu_tenant_id' is neither a valid DNS name, nor a valid external domain. Trace ID: 1e769860-8b10-479e-abf6-84f3fac7ae00 Correlation ID: 50b2ae58-33be-4671-a3a0-c1283361a670 Timestamp: 2025-03-09 19:15:52Z","error_codes":[900023],"timestamp":"2025-03-09 19:15:52Z","trace_id":"1e769860-8b10-479e-abf6-84f3fac7ae00","correlation_id":"50b2ae58-33be-4671-a3a0-c1283361a670","error_uri":"https://login.microsoftonline.com/error?code=900023"}
[2025-03-09T19:15:51.842+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=processar_emails_excel_operador_personalizado, task_id=ler_emails_microsoft_graph, run_id=scheduled__2025-03-08T00:00:00+00:00, execution_date=20250308T000000, start_date=20250309T191551, end_date=20250309T191551
[2025-03-09T19:15:51.862+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-09T19:15:51.863+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 151 for task ler_emails_microsoft_graph (Erro ao obter o token: 400, {"error":"invalid_request","error_description":"AADSTS900023: Specified tenant identifier 'seu_tenant_id' is neither a valid DNS name, nor a valid external domain. Trace ID: 1e769860-8b10-479e-abf6-84f3fac7ae00 Correlation ID: 50b2ae58-33be-4671-a3a0-c1283361a670 Timestamp: 2025-03-09 19:15:52Z","error_codes":[900023],"timestamp":"2025-03-09 19:15:52Z","trace_id":"1e769860-8b10-479e-abf6-84f3fac7ae00","correlation_id":"50b2ae58-33be-4671-a3a0-c1283361a670","error_uri":"https://login.microsoftonline.com/error?code=900023"}; 1166)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/extrai_email_operator.py", line 25, in execute
    token = self._get_access_token()
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/extrai_email_operator.py", line 43, in _get_access_token
    raise Exception(f"Erro ao obter o token: {response.status_code}, {response.text}")
Exception: Erro ao obter o token: 400, {"error":"invalid_request","error_description":"AADSTS900023: Specified tenant identifier 'seu_tenant_id' is neither a valid DNS name, nor a valid external domain. Trace ID: 1e769860-8b10-479e-abf6-84f3fac7ae00 Correlation ID: 50b2ae58-33be-4671-a3a0-c1283361a670 Timestamp: 2025-03-09 19:15:52Z","error_codes":[900023],"timestamp":"2025-03-09 19:15:52Z","trace_id":"1e769860-8b10-479e-abf6-84f3fac7ae00","correlation_id":"50b2ae58-33be-4671-a3a0-c1283361a670","error_uri":"https://login.microsoftonline.com/error?code=900023"}
[2025-03-09T19:15:51.924+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-09T19:15:52.099+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-09T19:15:52.104+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
