[2025-03-13T00:00:04.995+0000] {processor.py:186} INFO - Started process (PID=3828) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:00:04.996+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:00:04.997+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:00:04.997+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:00:05.012+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:00:05.011+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:00:05.013+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:00:05.032+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.043 seconds
[2025-03-13T00:00:35.472+0000] {processor.py:186} INFO - Started process (PID=3894) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:00:35.473+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:00:35.474+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:00:35.474+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:00:35.488+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:00:35.487+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:00:35.488+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:00:35.508+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.041 seconds
[2025-03-13T00:01:05.621+0000] {processor.py:186} INFO - Started process (PID=3960) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:01:05.622+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:01:05.623+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:01:05.623+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:01:05.638+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:01:05.637+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:01:05.639+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:01:05.660+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.044 seconds
[2025-03-13T00:01:36.514+0000] {processor.py:186} INFO - Started process (PID=4026) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:01:36.515+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:01:36.516+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:01:36.516+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:01:36.528+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:01:36.527+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:01:36.529+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:01:36.550+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.041 seconds
[2025-03-13T00:02:07.204+0000] {processor.py:186} INFO - Started process (PID=4092) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:02:07.205+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:02:07.207+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:02:07.207+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:02:07.229+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:02:07.227+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:02:07.230+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:02:07.263+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.070 seconds
[2025-03-13T00:02:37.708+0000] {processor.py:186} INFO - Started process (PID=4158) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:02:37.709+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:02:37.711+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:02:37.711+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:02:37.724+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:02:37.723+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:02:37.725+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:02:37.745+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.043 seconds
[2025-03-13T00:03:08.583+0000] {processor.py:186} INFO - Started process (PID=4224) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:03:08.584+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:03:08.586+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:03:08.585+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:03:08.600+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:03:08.599+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:03:08.600+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:03:08.621+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.043 seconds
[2025-03-13T00:03:39.450+0000] {processor.py:186} INFO - Started process (PID=4290) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:03:39.451+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:03:39.452+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:03:39.452+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:03:39.467+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:03:39.466+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:03:39.467+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:03:39.487+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.043 seconds
[2025-03-13T00:04:10.307+0000] {processor.py:186} INFO - Started process (PID=4356) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:04:10.308+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:04:10.310+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:04:10.309+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:04:10.324+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:04:10.323+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:04:10.325+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:04:10.342+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.040 seconds
[2025-03-13T00:04:41.186+0000] {processor.py:186} INFO - Started process (PID=4422) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:04:41.187+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:04:41.189+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:04:41.189+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:04:41.204+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:04:41.203+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:04:41.205+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:04:41.224+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.043 seconds
[2025-03-13T00:05:11.655+0000] {processor.py:186} INFO - Started process (PID=4488) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:05:11.656+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:05:11.657+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:05:11.657+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:05:11.673+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:05:11.672+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:05:11.674+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:05:11.692+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.042 seconds
[2025-03-13T00:05:42.292+0000] {processor.py:186} INFO - Started process (PID=4554) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:05:42.293+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:05:42.295+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:05:42.294+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:05:42.310+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:05:42.308+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:05:42.310+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:05:42.329+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.042 seconds
[2025-03-13T00:06:12.781+0000] {processor.py:186} INFO - Started process (PID=4620) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:06:12.782+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:06:12.783+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:06:12.783+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:06:12.797+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:06:12.796+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:06:12.798+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:06:12.818+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.043 seconds
[2025-03-13T00:06:42.979+0000] {processor.py:186} INFO - Started process (PID=4686) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:06:42.980+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:06:42.981+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:06:42.981+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:06:42.995+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:06:42.994+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:06:42.995+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:06:43.026+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.052 seconds
[2025-03-13T00:07:13.461+0000] {processor.py:186} INFO - Started process (PID=4752) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:07:13.462+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:07:13.463+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:07:13.463+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:07:13.477+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:07:13.476+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:07:13.478+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:07:13.496+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.041 seconds
[2025-03-13T00:07:43.798+0000] {processor.py:186} INFO - Started process (PID=4818) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:07:43.799+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:07:43.800+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:07:43.800+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:07:43.815+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:07:43.814+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:07:43.815+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:07:43.835+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.042 seconds
[2025-03-13T00:08:14.073+0000] {processor.py:186} INFO - Started process (PID=4884) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:08:14.073+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:08:14.075+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:08:14.074+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:08:14.088+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:08:14.087+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:08:14.088+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:08:14.107+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.040 seconds
[2025-03-13T00:08:44.286+0000] {processor.py:186} INFO - Started process (PID=4950) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:08:44.287+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:08:44.289+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:08:44.288+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:08:44.307+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:08:44.306+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:08:44.308+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:08:44.331+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.051 seconds
[2025-03-13T00:09:14.756+0000] {processor.py:186} INFO - Started process (PID=5016) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:09:14.757+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:09:14.759+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:09:14.759+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:09:14.781+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:09:14.779+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:09:14.782+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:09:14.806+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.057 seconds
[2025-03-13T00:09:45.115+0000] {processor.py:186} INFO - Started process (PID=5082) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:09:45.116+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:09:45.117+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:09:45.117+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:09:45.131+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:09:45.130+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:09:45.132+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:09:45.151+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.041 seconds
[2025-03-13T00:10:15.443+0000] {processor.py:186} INFO - Started process (PID=5147) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:10:15.444+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:10:15.446+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:10:15.445+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:10:15.461+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:10:15.460+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:10:15.462+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:10:15.480+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.042 seconds
[2025-03-13T00:10:46.003+0000] {processor.py:186} INFO - Started process (PID=5212) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:10:46.004+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:10:46.005+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:10:46.005+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:10:46.023+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:10:46.022+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:10:46.024+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:10:46.043+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.045 seconds
[2025-03-13T00:11:16.569+0000] {processor.py:186} INFO - Started process (PID=5278) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:11:16.570+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:11:16.571+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:11:16.571+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:11:16.585+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:11:16.584+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:11:16.586+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:11:16.607+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.042 seconds
[2025-03-13T00:11:46.699+0000] {processor.py:186} INFO - Started process (PID=5344) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:11:46.700+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:11:46.701+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:11:46.701+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:11:46.716+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:11:46.715+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:11:46.717+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:11:46.740+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.046 seconds
[2025-03-13T00:12:17.178+0000] {processor.py:186} INFO - Started process (PID=5409) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:12:17.179+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:12:17.181+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:12:17.181+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:12:17.198+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:12:17.197+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:12:17.199+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:12:17.221+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.049 seconds
[2025-03-13T00:12:47.489+0000] {processor.py:186} INFO - Started process (PID=5475) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:12:47.491+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:12:47.492+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:12:47.492+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:12:47.507+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:12:47.506+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:12:47.508+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:12:47.530+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.046 seconds
[2025-03-13T00:13:17.712+0000] {processor.py:186} INFO - Started process (PID=5540) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:13:17.713+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:13:17.715+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:13:17.715+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:13:17.735+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:13:17.734+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:13:17.736+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:13:17.766+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.059 seconds
[2025-03-13T00:13:47.856+0000] {processor.py:186} INFO - Started process (PID=5606) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:13:47.857+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:13:47.859+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:13:47.859+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:13:47.881+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:13:47.879+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:13:47.882+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:13:47.909+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.061 seconds
[2025-03-13T00:14:18.329+0000] {processor.py:186} INFO - Started process (PID=5672) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:14:18.330+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:14:18.331+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:14:18.331+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:14:18.345+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:14:18.344+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:14:18.345+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:14:18.365+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.041 seconds
[2025-03-13T00:14:48.984+0000] {processor.py:186} INFO - Started process (PID=5738) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:14:48.985+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:14:48.986+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:14:48.986+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:14:49.002+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:14:49.001+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:14:49.003+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:14:49.025+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.047 seconds
[2025-03-13T00:15:19.160+0000] {processor.py:186} INFO - Started process (PID=5804) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:15:19.161+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:15:19.162+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:15:19.162+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:15:19.179+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:15:19.178+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:15:19.180+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:15:19.203+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.049 seconds
[2025-03-13T00:15:49.382+0000] {processor.py:186} INFO - Started process (PID=5870) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:15:49.383+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:15:49.384+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:15:49.384+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:15:49.398+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:15:49.397+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:15:49.399+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:15:49.418+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.042 seconds
[2025-03-13T00:16:20.037+0000] {processor.py:186} INFO - Started process (PID=5935) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:16:20.038+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:16:20.039+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:16:20.039+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:16:20.053+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:16:20.052+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:16:20.054+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:16:20.075+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.044 seconds
[2025-03-13T00:16:50.390+0000] {processor.py:186} INFO - Started process (PID=6001) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:16:50.391+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:16:50.392+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:16:50.392+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:16:50.410+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:16:50.409+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:16:50.411+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:16:50.431+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.049 seconds
[2025-03-13T00:17:20.671+0000] {processor.py:186} INFO - Started process (PID=6067) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:17:20.672+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:17:20.673+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:17:20.673+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:17:20.694+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:17:20.693+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:17:20.694+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:17:20.716+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.050 seconds
[2025-03-13T00:17:51.785+0000] {processor.py:186} INFO - Started process (PID=6133) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:17:51.795+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:17:51.800+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:17:51.799+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:17:51.865+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:17:51.862+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:17:51.871+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:17:51.961+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.188 seconds
[2025-03-13T00:18:22.354+0000] {processor.py:186} INFO - Started process (PID=6199) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:18:22.355+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:18:22.357+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:18:22.356+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:18:22.376+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:18:22.375+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:18:22.378+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:18:22.403+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.054 seconds
[2025-03-13T00:18:52.994+0000] {processor.py:186} INFO - Started process (PID=6265) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:18:52.995+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:18:52.999+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:18:52.998+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:18:53.022+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:18:53.021+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:18:53.023+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:18:53.050+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.066 seconds
[2025-03-13T00:19:23.221+0000] {processor.py:186} INFO - Started process (PID=6331) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:19:23.223+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:19:23.225+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:19:23.225+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:19:23.244+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:19:23.243+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:19:23.245+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:19:23.266+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.053 seconds
[2025-03-13T00:19:53.518+0000] {processor.py:186} INFO - Started process (PID=6397) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:19:53.520+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:19:53.523+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:19:53.522+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:19:53.540+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:19:53.539+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:19:53.541+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:19:53.563+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.050 seconds
[2025-03-13T00:20:24.052+0000] {processor.py:186} INFO - Started process (PID=6463) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:20:24.053+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:20:24.055+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:20:24.054+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:20:24.078+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:20:24.077+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:20:24.079+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:20:24.102+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.055 seconds
[2025-03-13T00:20:54.773+0000] {processor.py:186} INFO - Started process (PID=6535) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:20:54.775+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:20:54.777+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:20:54.776+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:20:54.805+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:20:54.803+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:20:54.808+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:20:54.846+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.086 seconds
[2025-03-13T00:21:25.309+0000] {processor.py:186} INFO - Started process (PID=6601) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:21:25.311+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:21:25.313+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:21:25.312+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:21:25.334+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:21:25.333+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:21:25.335+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:21:25.362+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.061 seconds
[2025-03-13T00:21:55.680+0000] {processor.py:186} INFO - Started process (PID=6667) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:21:55.682+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:21:55.683+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:21:55.683+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:21:55.700+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:21:55.699+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:21:55.701+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:21:55.722+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.049 seconds
[2025-03-13T00:22:26.075+0000] {processor.py:186} INFO - Started process (PID=6733) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:22:26.076+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:22:26.077+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:22:26.077+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:22:26.091+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:22:26.090+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:22:26.092+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:22:26.112+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.043 seconds
[2025-03-13T00:22:56.675+0000] {processor.py:186} INFO - Started process (PID=6799) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:22:56.676+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:22:56.678+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:22:56.677+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:22:56.694+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:22:56.693+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:22:56.695+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:22:56.715+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.046 seconds
[2025-03-13T00:23:27.736+0000] {processor.py:186} INFO - Started process (PID=6865) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:23:27.737+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:23:27.738+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:23:27.738+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:23:27.752+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:23:27.751+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:23:27.752+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:23:27.770+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.039 seconds
[2025-03-13T00:23:57.887+0000] {processor.py:186} INFO - Started process (PID=6931) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:23:57.888+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:23:57.889+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:23:57.889+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:23:57.909+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:23:57.908+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:23:57.910+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:23:57.932+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.051 seconds
[2025-03-13T00:24:28.131+0000] {processor.py:186} INFO - Started process (PID=6997) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:24:28.133+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:24:28.135+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:24:28.135+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:24:28.203+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:24:28.201+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:24:28.215+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:24:28.273+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.161 seconds
[2025-03-13T00:24:59.146+0000] {processor.py:186} INFO - Started process (PID=7063) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:24:59.147+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:24:59.149+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:24:59.148+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:24:59.166+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:24:59.165+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:24:59.168+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:24:59.190+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.050 seconds
[2025-03-13T00:25:29.567+0000] {processor.py:186} INFO - Started process (PID=7122) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:25:29.568+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:25:29.570+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:25:29.569+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:25:29.590+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:25:29.589+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:25:29.591+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:25:29.617+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.056 seconds
[2025-03-13T00:26:01.029+0000] {processor.py:186} INFO - Started process (PID=7188) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:26:01.031+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:26:01.032+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:26:01.031+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:26:01.049+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:26:01.048+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:26:01.050+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:26:01.072+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.049 seconds
[2025-03-13T00:26:32.054+0000] {processor.py:186} INFO - Started process (PID=7251) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:26:32.055+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:26:32.057+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:26:32.056+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:26:32.075+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:26:32.074+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:26:32.076+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:26:32.098+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.050 seconds
[2025-03-13T00:27:02.438+0000] {processor.py:186} INFO - Started process (PID=7309) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:27:02.439+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:27:02.440+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:27:02.440+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:27:02.456+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:27:02.455+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:27:02.457+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:27:02.477+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.044 seconds
[2025-03-13T00:27:32.554+0000] {processor.py:186} INFO - Started process (PID=7374) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:27:32.555+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:27:32.556+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:27:32.556+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:27:32.571+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:27:32.570+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:27:32.571+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:27:32.590+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.042 seconds
[2025-03-13T00:28:02.887+0000] {processor.py:186} INFO - Started process (PID=7441) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:28:02.888+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:28:02.890+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:28:02.889+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:28:02.906+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:28:02.905+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:28:02.907+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:28:02.927+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.049 seconds
[2025-03-13T00:28:33.001+0000] {processor.py:186} INFO - Started process (PID=7506) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:28:33.003+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:28:33.005+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:28:33.005+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:28:33.022+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:28:33.021+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:28:33.023+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:28:33.049+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.056 seconds
[2025-03-13T00:29:03.120+0000] {processor.py:186} INFO - Started process (PID=7572) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:29:03.121+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:29:03.122+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:29:03.122+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:29:03.135+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:29:03.134+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:29:03.135+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:29:03.152+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.037 seconds
[2025-03-13T00:29:33.901+0000] {processor.py:186} INFO - Started process (PID=7639) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:29:33.902+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:29:33.904+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:29:33.903+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:29:33.916+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:29:33.915+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:29:33.917+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:29:33.937+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.041 seconds
[2025-03-13T00:30:04.821+0000] {processor.py:186} INFO - Started process (PID=7705) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:30:04.822+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:30:04.823+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:30:04.823+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:30:04.838+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:30:04.837+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:30:04.839+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:30:04.859+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.044 seconds
[2025-03-13T00:30:35.090+0000] {processor.py:186} INFO - Started process (PID=7771) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:30:35.091+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:30:35.092+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:30:35.092+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:30:35.108+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:30:35.107+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:30:35.109+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:30:35.129+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.044 seconds
[2025-03-13T00:31:05.718+0000] {processor.py:186} INFO - Started process (PID=7837) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:31:05.719+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:31:05.721+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:31:05.721+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:31:05.743+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:31:05.741+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:31:05.744+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:31:05.790+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.081 seconds
[2025-03-13T00:31:36.393+0000] {processor.py:186} INFO - Started process (PID=7903) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:31:36.395+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:31:36.396+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:31:36.396+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:31:36.413+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:31:36.412+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:31:36.413+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:31:36.435+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.047 seconds
[2025-03-13T00:32:06.800+0000] {processor.py:186} INFO - Started process (PID=7969) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:32:06.801+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:32:06.802+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:32:06.802+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:32:06.817+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:32:06.816+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:32:06.817+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:32:06.838+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.044 seconds
[2025-03-13T00:32:37.610+0000] {processor.py:186} INFO - Started process (PID=8035) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:32:37.612+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:32:37.613+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:32:37.613+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:32:37.629+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:32:37.628+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:32:37.630+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:32:37.654+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.049 seconds
[2025-03-13T00:33:08.211+0000] {processor.py:186} INFO - Started process (PID=8096) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:33:08.214+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:33:08.217+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:33:08.216+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:33:08.257+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:33:08.256+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:33:08.258+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:33:08.281+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.081 seconds
[2025-03-13T00:33:38.652+0000] {processor.py:186} INFO - Started process (PID=8156) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:33:38.653+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:33:38.654+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:33:38.654+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:33:38.675+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:33:38.674+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:33:38.677+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:33:38.701+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.055 seconds
[2025-03-13T00:34:09.489+0000] {processor.py:186} INFO - Started process (PID=8222) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:34:09.490+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:34:09.491+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:34:09.491+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:34:09.505+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:34:09.504+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:34:09.505+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:34:09.526+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.042 seconds
[2025-03-13T00:34:40.370+0000] {processor.py:186} INFO - Started process (PID=8288) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:34:40.372+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:34:40.373+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:34:40.372+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:34:40.389+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:34:40.387+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:34:40.390+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:34:40.409+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.044 seconds
[2025-03-13T00:35:10.528+0000] {processor.py:186} INFO - Started process (PID=8354) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:35:10.529+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:35:10.531+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:35:10.531+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:35:10.547+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:35:10.546+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:35:10.548+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:35:10.569+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.047 seconds
[2025-03-13T00:35:41.099+0000] {processor.py:186} INFO - Started process (PID=8420) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:35:41.100+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:35:41.101+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:35:41.101+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:35:41.116+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:35:41.115+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:35:41.117+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:35:41.137+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.043 seconds
[2025-03-13T00:36:11.204+0000] {processor.py:186} INFO - Started process (PID=8485) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:36:11.205+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:36:11.206+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:36:11.206+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:36:11.219+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:36:11.218+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:36:11.220+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:36:11.241+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.042 seconds
[2025-03-13T00:36:41.476+0000] {processor.py:186} INFO - Started process (PID=8552) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:36:41.477+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:36:41.478+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:36:41.478+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:36:41.497+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:36:41.496+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:36:41.498+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:36:41.518+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.048 seconds
[2025-03-13T00:37:11.706+0000] {processor.py:186} INFO - Started process (PID=8618) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:37:11.707+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:37:11.708+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:37:11.708+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:37:11.725+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:37:11.724+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:37:11.726+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:37:11.751+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.050 seconds
[2025-03-13T00:37:42.169+0000] {processor.py:186} INFO - Started process (PID=8684) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:37:42.170+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:37:42.172+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:37:42.171+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:37:42.186+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:37:42.185+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:37:42.188+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:37:42.212+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.048 seconds
[2025-03-13T00:38:12.324+0000] {processor.py:186} INFO - Started process (PID=8750) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:38:12.325+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:38:12.326+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:38:12.326+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:38:12.342+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:38:12.341+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:38:12.343+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:38:12.365+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.046 seconds
[2025-03-13T00:38:42.623+0000] {processor.py:186} INFO - Started process (PID=8816) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:38:42.624+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:38:42.625+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:38:42.625+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:38:42.640+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:38:42.639+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:38:42.641+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:38:42.662+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.044 seconds
[2025-03-13T00:39:13.222+0000] {processor.py:186} INFO - Started process (PID=8881) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:39:13.223+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:39:13.224+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:39:13.224+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:39:13.240+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:39:13.239+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:39:13.241+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:39:13.260+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.043 seconds
[2025-03-13T00:39:44.188+0000] {processor.py:186} INFO - Started process (PID=8947) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:39:44.189+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:39:44.191+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:39:44.190+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:39:44.209+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:39:44.208+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:39:44.210+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:39:44.235+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.053 seconds
[2025-03-13T00:40:14.802+0000] {processor.py:186} INFO - Started process (PID=9013) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:40:14.803+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:40:14.804+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:40:14.804+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:40:14.821+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:40:14.820+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:40:14.821+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:40:14.845+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.050 seconds
[2025-03-13T00:40:45.096+0000] {processor.py:186} INFO - Started process (PID=9079) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:40:45.097+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:40:45.098+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:40:45.098+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:40:45.111+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:40:45.110+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:40:45.112+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:40:45.131+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.040 seconds
[2025-03-13T00:41:15.728+0000] {processor.py:186} INFO - Started process (PID=9145) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:41:15.729+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:41:15.731+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:41:15.730+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:41:15.746+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:41:15.745+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:41:15.747+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:41:15.766+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.044 seconds
[2025-03-13T00:41:45.841+0000] {processor.py:186} INFO - Started process (PID=9210) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:41:45.843+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:41:45.845+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:41:45.844+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:41:45.859+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:41:45.858+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:41:45.860+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:41:45.878+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.042 seconds
[2025-03-13T00:42:16.157+0000] {processor.py:186} INFO - Started process (PID=9277) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:42:16.158+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:42:16.159+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:42:16.158+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:42:16.173+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:42:16.172+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:42:16.174+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:42:16.193+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.041 seconds
[2025-03-13T00:42:46.991+0000] {processor.py:186} INFO - Started process (PID=9343) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:42:46.992+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:42:46.994+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:42:46.993+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:42:47.007+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:42:47.006+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:42:47.007+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:42:47.027+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.041 seconds
[2025-03-13T00:43:17.434+0000] {processor.py:186} INFO - Started process (PID=9409) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:43:17.435+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:43:17.437+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:43:17.437+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:43:17.456+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:43:17.455+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:43:17.458+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:43:17.498+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.072 seconds
[2025-03-13T00:43:47.878+0000] {processor.py:186} INFO - Started process (PID=9475) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:43:47.879+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:43:47.880+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:43:47.880+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:43:47.895+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:43:47.893+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:43:47.895+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:43:47.915+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.045 seconds
[2025-03-13T00:44:18.787+0000] {processor.py:186} INFO - Started process (PID=9541) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:44:18.789+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:44:18.790+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:44:18.789+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:44:18.806+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:44:18.805+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:44:18.807+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:44:18.830+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.048 seconds
[2025-03-13T00:44:49.564+0000] {processor.py:186} INFO - Started process (PID=9607) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:44:49.565+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:44:49.567+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:44:49.566+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:44:49.581+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:44:49.580+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:44:49.582+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:44:49.600+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.043 seconds
[2025-03-13T00:45:20.740+0000] {processor.py:186} INFO - Started process (PID=9673) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:45:20.755+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:45:20.767+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:45:20.766+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:45:20.834+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:45:20.832+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:45:20.843+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:45:20.899+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.181 seconds
[2025-03-13T00:45:51.455+0000] {processor.py:186} INFO - Started process (PID=9738) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:45:51.456+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:45:51.458+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:45:51.457+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:45:51.471+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:45:51.469+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:45:51.472+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:45:51.499+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.049 seconds
[2025-03-13T00:46:22.301+0000] {processor.py:186} INFO - Started process (PID=9804) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:46:22.302+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:46:22.304+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:46:22.303+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:46:22.318+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:46:22.317+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:46:22.319+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:46:22.339+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.043 seconds
[2025-03-13T00:46:52.500+0000] {processor.py:186} INFO - Started process (PID=9870) to work on /opt/airflow/dags/pipeline.py
[2025-03-13T00:46:52.502+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-03-13T00:46:52.505+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:46:52.504+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-03-13T00:46:52.521+0000] {logging_mixin.py:190} INFO - [2025-03-13T00:46:52.520+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 112
    def concatenar
                  ^
SyntaxError: expected '('
[2025-03-13T00:46:52.522+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-03-13T00:46:52.540+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.045 seconds
